### ISSUE TITLE
CountableFeatures: support for unitary prices

### ISSUE THREAD

**Issue by Aerendir** [Aerendir/bundle-features#1]
The configuration should be something like this:

```yaml
automatic_reminders:
    type: countable
    cumulable: true
    unitary_price:
        EUR:
            monthly: 1000
            yearly: 10000
        packs:
            ...
```

Find a way to differentiate the forms. Maybe adding a suffix like `_packs` and `_units` may work.

This will break the setting of the default value.

Then is necessary to find a way to calculate the right `instantPrice` and to save the amount of units bought. More, is necessary to decide what happens in case there are packs set.

For example, if exists a pack with 50 units and the user buys 55, the 50 units should be paid following the `packs` price or the `unitary_price`? The remaining 5 units will be paid for sure following the `unitary_price`.
