### ISSUE TITLE
Upgrade the way a free pack is created in `countable`

### ISSUE THREAD

**Issue by Aerendir** [Aerendir/bundle-features#59]
Currently it is possible to set a free plan with this config:

```yaml
shq_features:
    ...
    sets:
       ....
            features:
                feature_name:
                    ...
                    packs:
                        50: ~
                        ...
```

This causes an empty array in the config that causes a lot of troubles in the code because we have to deal with an empty array.

# What to do
Do not allow an empty configuration. Instead, require an explicit configuration set to 0:

```yaml
shq_features:
    ...
    sets:
       ....
            features:
                feature_name:
                    ...
                    packs:
                        50:
                            EUR:
                                monthly: 0
                                yearly: 0
                        ...
```

**v0.12.0
- [ ] Deprecate the use of an empty configuration

**v0.13.0**
- [ ] Refact `SerendipityHQ\Bundle\FeaturesBundle\DependencyInjection\Configuration` to not allow an empty config
- [ ] Refact `SerendipityHQ\Bundle\FeaturesBundle\Property\HasRecurringPricesProperty::setTax()` to not allow `null` values (line 171)
